authorName: ligong
experimentName: test_mpl
trialConcurrency: 8
maxExecDuration: 1h
maxTrialNum: 200
trainingServicePlatform: local
useAnnotation: true 
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python scripts/site_exp.py
  codeDir: .
  gpuNum: 0
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: minimize
    start_step: 5
