authorName: ligong
experimentName: test_mpl
trialConcurrency: 4
maxExecDuration: 1h
maxTrialNum: 40
trainingServicePlatform: local
useAnnotation: true 
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python scripts/test_mpl.py
  codeDir: .
  gpuNum: 0
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: minimize
    start_step: 5
